### ISSUE TITLE
Package simply not works

### ISSUE THREAD

**Issue by thecyberd3m0n** [BiteBit/node-feedparser#1]
I tried to use your package as dependency and getting data from here:
http://feed.rutracker.org/atom/f/1880.atom

but unfortunately package does not seems to work. All tests is failing even from it original sources 

  ```
node-feedparser` unit test
    1) rss without tags
    2) atom without tags
    3) rss with tags
    4) atom with tags


  0 passing (8s)
  4 failing

  1) node-feedparser unit test rss without tags:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  2) node-feedparser unit test atom without tags:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  3) node-feedparser unit test rss with tags:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  4) node-feedparser unit test atom with tags:
     Uncaught Error: Not a feed
      at FeedParser.handleEnd (node_modules/feedparser/main.js:123:13)
      at Object.SAXStream._parser.onend (node_modules/sax/lib/sax.js:184:8)
      at emit (node_modules/sax/lib/sax.js:615:33)
      at end (node_modules/sax/lib/sax.js:654:3)
      at Object.SAXParser.end (node_modules/sax/lib/sax.js:149:24)
      at SAXStream.end (node_modules/sax/lib/sax.js:234:16)
      at FeedParser._flush (node_modules/feedparser/main.js:1066:17)
      at FeedParser.<anonymous> (node_modules/readable-stream/lib/_stream_transform.js:135:12)
      at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:371:12)
      at endWritable (node_modules/readable-stream/lib/_stream_writable.js:378:3)
      at FeedParser.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:356:5)
      at StringStream.pipe (node_modules/string-stream/index.js:34:8)
      at module.exports (index.js:46:12)
      at Request._callback (test/index.js:14:16)
      at self.callback (node_modules/request/request.js:186:22)
      at Request.onRequestError (node_modules/request/request.js:845:8)
      at Socket.socketErrorListener (_http_client.js:308:9)
      at emitErrorNT (net.js:1271:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

```
I very like the idea of your parser so please if it possible add some fixes. I even don't know could I read needed RSS source using this

**Comment by BiteBit** [comment]
Sorry, i have't test it for a long time, i will do some test and add this module to travis.
If i find some bug, i will fix it as soon as possible.

**Comment by amazing-gao** [comment]
Hi, i have make some tests on travis. It's ok to parse http://feed.rutracker.org/atom/f/1880.atom.
I think it could be your network's problem.
There is travis link [node-feedparser](https://travis-ci.org/BiteBit/node-feedparser).
